import React, { useContext, useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { MainContext } from '../context/mainContext'

export default function Home() {
  const { logout } = useContext(MainContext)

  return (
    <div>
      <Head>
        <title>NetChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

    <Link href={'/signin'}><a>go</a></Link>
    <Link href={'/signup'}><a>go1</a></Link>
    <button onClick={logout}>logout</button>

    </div>
  )
}
