import React, { useContext, useState, useEffect } from 'react'
import { MdSecurity } from 'react-icons/md'
import Link from 'next/link'
import Head from 'next/head'
import { MainContext } from '../context/mainContext'
import { AiOutlineLoading3Quarters } from 'react-icons/ai'

const signin = () => {
  const { signIn, signInRemember, isDark, auth, router } = useContext(MainContext)

  const [signingin, setSigningin] = useState(false)
  const [credentials, setCredentials] = useState({ email: '', password: '' })
  const [remember, setRemember] = useState(true)

  // useEffect(() => {
  //   if(auth.currentUser){
  //     router.push('/')
  //   }
  // }, [auth.currentUser])

  const onChange = (e) => {
    setCredentials({ ...credentials, [e.target.name]: e.target.value })
  }

  const onSubmit = async (e) => {
    e.preventDefault()
    setSigningin(true)
    if(remember){
      await signInRemember(credentials)
    }
    else{
      await signIn(credentials)
    }
    setSigningin(false)
  }


  return (
    <>
      <Head>
        <title>NetChat | Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      
      <div className={`min-h-screen flex items-center justify-center px-4 ${isDark?'bg-gray-900 text-gray-300':'bg-white text-gray-900'}`}>
        <div className={`max-w-md w-full space-y-3 h-min mx-auto my-auto ${signingin ? 'pointer-events-none' : ''}`}>
          <div>
            <img
              className="mx-auto h-20 w-auto"
              src={`/favicon.svg`}
              alt="Logo"
            />
            <h2 className={`mt-4 text-center text-2xl sm:text-3xl font-extrabold`}>Sign in to your account</h2>
          </div>
          <form onSubmit={onSubmit} className="mt-2 space-y-6" action="#" method="POST">
            <div className="shadow-sm -space-y-px">
              <div>
                <label htmlFor="email" className="sr-only">
                  Email
                </label>
                <input
                  disabled={signingin}
                  onChange={onChange}
                  id="email"
                  name="email"
                  type="email"
                  required
                  className={`rounded-xl border hover:border-blue-600 ${isDark?'border-gray-800 bg-gray-800 text-gray-300':'border-gray-200 bg-gray-200 text-gray-900'}  w-full outline-none p-2 h-11/12 resize-none mb-2`}
                  placeholder="Email"
                />
              </div>

              <div>
                <label htmlFor="password" className="sr-only">
                  Password
                </label>
                <input
                  disabled={signingin}
                  onChange={onChange}
                  id="password"
                  name="password"
                  type="password"
                  required
                  minLength={6}
                  className={`rounded-xl border hover:border-blue-600 ${isDark?'border-gray-800 bg-gray-800 text-gray-300':'border-gray-200 bg-gray-200 text-gray-900'}  w-full outline-none p-2 h-11/12 resize-none mb-2`}
                  placeholder="Password"
                />
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <input
                  disabled={signingin}
                  onChange={(e) => {
                    setRemember(e.target.checked)
                   }}
                  checked={remember}
                  id="rememberme"
                  name="rememberme"
                  type="checkbox"
                  
                  className={`h-4 w-4 text-blue-600 focus:ring-blue-700 ${isDark?'border-gray-300':'border-gray-900'} rounded-lg`}
                />
                <label htmlFor="remember-me" className="ml-2 block text-sm">
                  Remember me
                </label>
              </div>

              <div className="text-sm">
                <Link href="/sendLink">
                  <a disabled={signingin} className="font-medium hover:underline underline-offset-2 text-blue-600 hover:text-blue-700">
                    Forgot your password?
                  </a>
                </Link>
              </div>
            </div>

            <div>
              <button
                disabled={signingin}
                type="submit"
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-xl text-white bg-blue-600 hover:bg-blue-700 "
              >
                <span className="absolute left-0 inset-y-0 flex items-center pl-3">
                  <MdSecurity className="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" size={24} />
                </span>
                {signingin ?
                  <AiOutlineLoading3Quarters className='animate-spin' size={24} />
                  :
                  'Sign in'
                }
              </button>
            </div>
            <div className="text-sm flex justify-between">
              Don't have an account?
              <Link href="/signup">
                <a disabled={signingin} className="font-medium hover:underline underline-offset-2 text-blue-600 hover:text-blue-700">
                  Register here
                </a>
              </Link>
            </div>
          </form>
        </div>
      </div>
    </>
  )
}

export default signin